language: rust
rust:
  - stable
before_script:
  - rustup component add clippy 
  - cargo install cargo-audit
script:
  - cargo build --verbose --all
    #  - cd gehma_server && cargo test --verbose --all
  - cargo clippy --all-features -- -D warnings
  - cargo audit -D
