version: '3.3'
services:
   db:
     image: postgres:12
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       POSTGRES_USER: root 
       POSTGRES_PASSWORD: root 
       POSTGRES_DB: sprechstunde 
     ports:
       - "5432:5432"
   server:
     depends_on:
       - db
     image: kper1337/gehma_server
     build: .
     ports:
       - "443:443"
     restart: always
volumes:
    db_data: {}
