ALTER TABLE events DROP CONSTRAINT events_pkey;
ALTER TABLE events ALTER COLUMN id TYPE UUID;
ALTER TABLE events ADD PRIMARY KEY (id);
ALTER TABLE events ADD COLUMN closing TIMESTAMP NOT NULL;
ALTER TABLE events ALTER COlUMN href TYPE VARCHAR(1024);

