ALTER TABLE users ADD COLUMN hash_tele_num VARCHAR(256);

ALTER TABLE blacklist ADD COLUMN blocker VARCHAR(256) REFERENCES users (hash_tele_num) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE blacklist ADD COLUMN blocked VARCHAR(256) REFERENCES users (hash_tele_num) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE contacts ADD COLUMN id SERIAL NOT NULL;
ALTER TABLE contacts ADD COLUMN from_tele_num VARCHAR(256) NOT NULL;
